### ISSUE TITLE
Open Slide Import error in python jupyter notebook 

### ISSUE THREAD

**Issue by pranathichunduru** [openslide/openslide#288] opened 2020-03-18 18:23 UTC
## Context
I am unable to import open-slide python in my jupyter notebook(virtual environment)

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Red Hat Enterprise Linux Workstation.Version- 7.7 (Maipo)
**Platform** (e.g. 64-bit x86, 32-bit ARM):  Linux 3.10.0-1062.12.1.el7.x86_64
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): .svs

## Details
```
OSError                                   Traceback (most recent call last)
<ipython-input-2-1d3bc907299c> in <module>
     16 print(os.environ["PATH"])
     17 
---> 18 import openslide
     19 # from openslide import OpenSlide, OpenSlideUnsupportedFormatError
     20 

/working/lupolab/pranathi/conda/envs/python3titan/lib/python3.6/site-packages/openslide/__init__.py in <module>
     27 from PIL import Image
     28 
---> 29 from openslide import lowlevel
     30 
     31 # For the benefit of library users

/working/lupolab/pranathi/conda/envs/python3titan/lib/python3.6/site-packages/openslide/lowlevel.py in <module>
     58         _lib = cdll.LoadLibrary(_lib)
     59 else:
---> 60     _lib = cdll.LoadLibrary('libopenslide.so.0')
     61 
     62 try:

/working/lupolab/pranathi/conda/envs/pchunduru/lib/python3.6/ctypes/__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

/working/lupolab/pranathi/conda/envs/pchunduru/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

```

I installed  open-slide using anaconda in my virtual environment:
`conda install -c bioconda openslide`

Installed openslide python using:
`conda install -c bioconda openslide-python`

After looking up on stackoverflow and github forums. I tried adding
`# os.environ["PATH"] =  "path/openslide/bin"  + ":" + os.environ["PATH"]`. in lowlevel.py file
However I cannot find bin folder in openslide. 
libopenslide.so.0 This file exists in python libraries (in virtual environment) but not in openslide.

I am trying to use openslide for digital pathology image analysis that are in .svs format.
I am scripting my code in python.
Also I donot have root access to use "yum install openslide" von linux platform ,since I am working on shared server and I am not the admin.

Please let me know if you need any further info to understand the issue better.
Appreciate any help !

**Comment by bgilbert** [comment] 2020-09-13 07:13
Duplicate of https://github.com/openslide/openslide-python/issues/77.

**Closed by bgilbert** 2020-09-13 07:13 UTC
Labels: invalid
