### ISSUE TITLE
Unable to install openslide-python in linux using pip python 3.6

### ISSUE THREAD

**Issue by Adamszk** [openslide/openslide#294] opened 2020-06-09 00:58 UTC
I am trying to install opensuse - python in virtual environment using python 3.6.   A bizarre situation:  It works when installing using python 2.7.   However it does not work with python 3.6 pip installation.  Other packages install without issue.
I have the following packages in venv:
(venv3) adam@linux-kyb0:~> pip list
Package         Version
--------------- -------
bitsets         0.7.16
concepts        0.9.2
cycler          0.10.0
features        0.5.12
fileconfig      0.5.10
graphviz        0.14
kiwisolver      1.2.0
matplotlib      3.2.1
numpy           1.18.5
pip             20.1.1
pyparsing       2.4.7
python-dateutil 2.8.1
setuptools      46.1.3
six             1.15.0
wheel           0.34.2

When I try to install openslide-python I get the following error message. 

(venv3) adam@linux-kyb0:~> pip install openslide-python
Collecting openslide-python
  Using cached openslide-python-1.1.1.tar.gz (312 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/adam/venv3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_v1__8o/openslide-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_v1__8o/openslide-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nsv75uhv                             
         cwd: /tmp/pip-install-g_v1__8o/openslide-python/                                                            
    Complete output (5 lines):                                                                                       
    Traceback (most recent call last):                                                                               
      File "<string>", line 1, in <module>                                                                           
      File "/tmp/pip-install-g_v1__8o/openslide-python/setup.py", line 2, in <module>                                
        from setuptools import setup, Extension, Feature                                                             
    ImportError: cannot import name 'Feature'                                                                        
    ----------------------------------------                                                                         
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Installation Issue: 
**OpenSUSE Leap 15.0**: 
**64-bit x86**:
**OpenSlide 3.4.0**: 
**All**:

**Comment by bgilbert** [comment] 2020-09-13 04:08
Duplicate of https://github.com/openslide/openslide-python/issues/80.

**Closed by bgilbert** 2020-09-13 04:08 UTC
Labels: invalid
