### ISSUE TITLE
3D Histech slides?

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#187] opened 2017-01-20 20:00 UTC
## Context

**Issue type** feature request 
**Operating system** Windows 7 
**Platform** 64-bit 
**Slide format** SVS, NDPI, MRXS 

## Details
Would it be possible to implement 3D histech support (MRXS) ? or other 3D file format support? This would be really nice.

**Comment by bgilbert** [comment] 2017-01-25 08:04
Per [discussion on openslide-users](https://lists.andrew.cmu.edu/pipermail/openslide-users/2017-January/001359.html), this is actually a request for multi-plane support.  Closing as duplicate of #31.

**Closed by bgilbert** 2017-01-25 08:04 UTC
