### ISSUE TITLE
How can I extract patches from the original whole slide images according to my predefined magnification times?

### ISSUE THREAD

**Issue by brisker** [openslide/openslide#178] opened 2016-07-01 14:59 UTC
I have used the python wrapper of openslide and got several folders containing lots of  patch images of WSI ,but  I can not   figure out what magnification times they belong to. Could you please tell me how to solve this problem? 
![image](https://cloud.githubusercontent.com/assets/13804492/16525587/b7683ba2-3fdf-11e6-817a-5dd53a3d2d4b.png)
![image](https://cloud.githubusercontent.com/assets/13804492/16525608/cc544d6c-3fdf-11e6-8d7d-4dd89228e05a.png)

**Comment by bgilbert** [comment] 2016-07-02 02:36
Duplicate of openslide/openslide-python#18.

**Closed by bgilbert** 2016-07-02 02:36 UTC

**Comment by brisker** [comment] 2016-07-02 03:02
@bgilbert   Could you please tell me how to do this?
