### ISSUE TITLE
openslide_read_region black-ish boxes for large regions

### ISSUE THREAD

**Issue by aaichert** [openslide/openslide#291] opened 2020-05-06 10:51 UTC
I am getting strange black-ish boxes when calling 
openslide_read_region(osr, data, 0,0, 0, w,h);
to read an entire slide at once.

## Context

**Issue type**: bug report 
**Operating system** (Ubuntu 18.04,20.04): 
**Platform** : 64-bit x86 
**OpenSlide version**:  via openslide-python 1.1.1  openslide 3.4.1, as well as latest built from source
**Slide format** SVS

## Details

I am using a slide with w,h, = 15656, 11184 
(public data from ICIAR'18 BACH challenge 01.svs)
and the same problem occurs for other slides from that data set.

I  get the same problems, when accessing just small patches, using other large slides and using various versions of operating systems and openslide versions. I originally observed the bug using openslide-python and then decided to use c++ to build the latest version from source. The bug persists.

The exact same issue was already described here:

https://stackoverflow.com/questions/56785530/is-there-any-problem-with-the-openslide-read-region-function

I was unable to find solutions or other descriptions of the same bug.

**Comment by aaichert** [comment] 2020-05-06 10:55
![slide_thumb](https://user-images.githubusercontent.com/1970285/81169226-ca4bfd00-8f98-11ea-9a19-099c7a22c8dc.PNG)

**Comment by JoshVarty** [comment] 2020-06-22 18:18
I have this issue as well on slides from The Cancer Genome Atlas. 

Here is an example slide (`865 MB`) if you would like a repro: https://portal.gdc.cancer.gov/files/0a5ac495-6b06-43bd-8a1b-7b9487bffb2d

I'm using python so my repro is:

```Python
import openslide
import matplotlib.pyplot as plt

img_path = 'path_to_file/0a5ac495-6b06-43bd-8a1b-7b9487bffb2d/TCGA-V1-A8MU-01Z-00-DX1.2C9CED13-5C2C-4FFB-AB0B-3904BAA4FEFF.svs'
slides = openslide.OpenSlide(img_path)
dims = slides.level_dimensions[1]
img = slides.read_region((0,0), 1, dims)
plt.imshow(img)
```

This gives this image: 
![image](https://user-images.githubusercontent.com/1249087/85321562-d7fb0a80-b492-11ea-8d35-548dfe3c7876.png)

The image begins to contain invalid data outside of a boundary of `4096x4096`.

I am not familiar with the codebase but this could be related: https://github.com/openslide/openslide/blob/master/src/openslide.c#L584

**Comment by JoshVarty** [comment] 2020-06-22 20:30
I have a workaround in which I perform multiple partial reads of the image and stitch them together.

I want to read from Level 1 because the Level 0 images are massive and I'm worried about memory pressure.

```Python

level = 1
downsample = int(slides.level_downsamples[level])
width, height = slides.level_dimensions[level]
read_size = 1024
# Calculate number of vertical and horizontal reads we'll need to take
vertical_reads = ((height - 1) // read_size) + 1
horizontal_reads = ((width - 1) // read_size) + 1

# Storage for all of our reads
all_imgs = []

for v_read in range(vertical_reads):
    for h_read in range(horizontal_reads):
        img = slides.read_region(((h_read * read_size)*downsample, (v_read * read_size)*downsample), level, (read_size, read_size))
        
        img_array = np.asarray(img)
        all_imgs.append(img_array)       
    
composite_image = np.zeros((vertical_reads * read_size, horizontal_reads * read_size, 4), dtype=np.uint8)

for i in range(vertical_reads):
    for j in range(horizontal_reads):
        
        start_i = i * read_size
        end_i = start_i + read_size
        
        start_j = j * read_size
        end_j = start_j + read_size
        
        composite_image[start_i:end_i, start_j:end_j,:] = all_imgs[(i * horizontal_reads) + j]
```

What's interesting here is that the composite image I create varies depending on the size of the reads (`read_size`) that I make.

For `read_size=1024`

![image](https://user-images.githubusercontent.com/1249087/85331933-0a156800-b4a5-11ea-94f2-f80970689cae.png)

For `read_size=2048` (Small amount of clipping)

![image](https://user-images.githubusercontent.com/1249087/85332033-2e714480-b4a5-11ea-8ac7-d23e9bc3aa48.png)

For `read_size=4096` (Large clipping)

![image](https://user-images.githubusercontent.com/1249087/85332109-506ac700-b4a5-11ea-8718-cf389562e5b6.png)


Increasing the size of my reads seems to increasing the areas of the image that are clipped. I don't know enough about `openslide` or image compression to speculate on the cause but it might be interesting for future readers.

**Comment by aaichert** [comment] 2020-06-22 21:38
Thanks for confirming. I have meanwhile confirmed the bug for TIFF files format as well...
Devs anyone?

**Comment by michaelsfr** [comment] 2020-10-29 12:46
We have also encountered this issue running Openslide on **Ubuntu 20.04**, while on Alpine 3.8 and Ubuntu 18.04 everything seems to work correctly. Building OpenSlice from source (master 3.4.1. / latest commit) or installing from the openslide-tools repo did not make any difference. We investigated that bug with the given openslide testdata. Affected WSI-formats are Aperio (svs), Mirax (mrsx) and Trestle (tif).

Attatched you can find serveral screenshots showing the differences of this bug for the stated formats.
The repo https://github.com/Gnork/openslide-ubuntu-focal-bug-report provides a script to reproduce the bug on Alpine and Ubuntu 18.04/20.04.

**Aperio** (Aperio/CMU-1.svs)
<img src="https://user-images.githubusercontent.com/36191174/97573932-c5698280-19ea-11eb-819f-921182bebf0a.png" width="400">

**Mirax** (Mirax/Mirax2.2-1.mrsx)
<img src="https://user-images.githubusercontent.com/36191174/97573951-c995a000-19ea-11eb-9032-34d90ef34d55.png" width="400">

**Trestle** (Trestle/CMU-1.tif)
<img src="https://user-images.githubusercontent.com/36191174/97573960-cc909080-19ea-11eb-9278-c2b8f48c5a49.png" width="400">

**Comment by joerosenthal** [comment] 2020-11-03 04:26
Seeing the same issue on Ubuntu 20.04 and Red Hat Enterprise Linux 8.2, but not on MacOS 10.15. Both Ubuntu and MacOS are using Openslide 3.4.1 with Cairo 1.16, glib 2.0, and gdk-pixbuf 2.40.

**Comment by GunnarFarneback** [comment] 2020-11-06 07:56
**Analysis**

At ContextVision we found this problem to be a manifestation of a more general pixel interpolation issue within OpenSlide. By comparing working and non-working setups it was eventually narrowed down to the `libpixman` dependency (via `libcairo`).

For *this issue* the versions 0.34, 0.36 and 0.40 of `libpixman` are all good. Version 0.38 is the problematic one (0.38.0, 0.38.2, 0.38.4 are all affected).

Since the most recent version 0.40 works, we have not tried to investigate what was the problem in the code, but if someone wants to dig deeper the next step would be to run a `git bisect` of the `pixman` source code to find the commits introducing and fixing the problem.

**Workaround**

Force a good version of `libpixman` to be loaded before a bad version, e.g. by using the `LD_PRELOAD` mechanism on Linux. On Ubuntu 18.04, where we ran into this issue via a Conda setup,

```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libpixman-1.so.0.34.0
```

is an effective workaround (make sure you have that file installed first though). If necessary, build `libpixman` from source. It's an easy build since it doesn't have any dependencies.

**Proper Solution**

Downgrade or upgrade your software environment to steer clear of `libpixman 0.38`.

**Comment by biocdeniz** [comment] 2020-11-20 17:04
We are using Python 3.6.8+ and this did the trick for us: `conda install pixman=0.36.0`

**Comment by YoniSchirris** [comment] 2021-01-27 13:21
I tested it today, and to my knowledge, the pixman v0.40.0 also doesn't have this issue anymore.

**Comment by virtualslidetools** [comment] 2022-02-02 07:14
libpixman 0.40.1 also works - at least with the Aperio Image files I have!

**Comment by bgilbert** [comment] 2022-09-06 07:34
Closing as duplicate of #278.  See https://github.com/openslide/openslide/issues/278#issuecomment-1237765515 for the current status.

**Closed by bgilbert** 2022-09-06 07:34 UTC
