### ISSUE TITLE
Reading scn file

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [openslide/openslide#266] opened 2019-03-07 14:54 UTC
vips copy myslide.scn mypyr.tif[tile,pyramid,compression=jpeg]
when i try the above command i get the following error.
openslide2vips: opening slide: Slides with dissimilar main images are not supported
Please help me with this issue.

 Thanks

**Comment by bgilbert** [comment] 2020-09-13 04:50
Duplicate of https://github.com/openslide/openslide/issues/189.

**Closed by bgilbert** 2020-09-13 04:50 UTC
Labels: invalid
