### ISSUE TITLE
read_region function leads to error

### ISSUE THREAD

**Issue by tnnandi** [openslide/openslide#561] opened 2024-02-11 02:41 UTC
### Operating system

Ubuntu

### Platform

64 bit x86

### OpenSlide version

4.0.0

### Slide format

svs

### Issue details

Hi,

When I try to use the read_region function as follows:
level = slide.get_best_level_for_downsample(32)
region = slide.read_region((0, 0), level, slide.level_dimensions[level])

I get the following error:
region = slide.read_region((0, 0), level, slide.level_dimensions[level])
*** ValueError: Argument is not writable

I'd appreciate it if you could suggest a solution.

Thanks

**Comment by bgilbert** [comment] 2024-02-11 06:46
Duplicate of https://github.com/openslide/openslide-python/issues/259

**Closed by bgilbert** 2024-02-11 06:46 UTC
Labels: defect
