### ISSUE TITLE
Read .SCN Error

### ISSUE THREAD

**Issue by DaihuaWei** [openslide/openslide#216] opened 2017-11-01 08:09 UTC
## Context
when i read a .SCN files  in python，report the error below:

openslide.lowlevel.OpenSlideError: Slides with dissimilar main images are not supported

**Comment by bgilbert** [comment] 2017-11-04 07:09
Duplicate of #99 or #189.

**Closed by bgilbert** 2017-11-04 07:09 UTC

**Comment by akulkarniNephrosant** [comment] 2023-05-10 00:00
is this resolved? I am having the same issue as above
openslide.lowlevel.OpenSlideError: Slides with dissimilar main images are not supported
