### ISSUE TITLE
Automake error './ltmain.sh' not found

### ISSUE THREAD

**Issue by j-hudecek** [openslide/openslide#301] opened 2020-08-24 20:45 UTC
## Context

**Issue type** : bug report
**Operating system** : CentOS 8
**Platform** : 64-bit x86
**OpenSlide version**: 3.4.1
**Slide format** :  N/A

## Details
When building from source, executing ``autoreconf -i`` on the repo I get 

    Automake error './ltmain.sh' not found

This is probably caused by a change introduced in Automake 1.6
    https://www.gnu.org/software/automake/manual/html_node/Error-required-file-ltmain_002esh-not-found.html
So, the first command when building should be ``libtoolize``. Perhaps the README could be updated?

**Comment by jaharkes** [comment] 2020-08-24 21:30
Perhaps you don't have libtool installed, because according to that page that functionality has been incorporated into autoreconf.

**Comment by j-hudecek** [comment] 2020-08-25 06:55
But then I wouldn't be able to just run libtoolize?

**Comment by jaharkes** [comment] 2020-08-25 14:48
It wasn't clear to me that you did run that, either way autoreconf is supposed to be responsible for running libtoolize so something odd is going on here.

Does `autoreconf -f -i` work? maybe some error leftover file made it skip installing ltmain.sh, with the `-f` it _should_ regenerate all files whether they are assumed to exist or not.

**Comment by jaharkes** [comment] 2020-09-11 17:36
I am unable to reproduce this on my on a fresh checkout of the repository. `autoreconf -i` ran libtoolize as it is supposed to do.
Closing this, feel free to reopen if you have more information related to this issue.

```
$ autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
$ libtoolize --version
libtoolize (GNU libtool) 2.4.6
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Closed by jaharkes** 2020-09-11 17:36 UTC
