### ISSUE TITLE
Fail to load huge size of NDPI

### ISSUE THREAD

**Issue by taku-i** [openslide/openslide#586] opened 2024-04-12 09:12 UTC
### Operating system

Windows 10

### Platform

64bit

### OpenSlide version

3.4.1

### Slide format

NDPI

### Issue details

Fail to load 6.9GB image.

Our environment:
 Version of OpenSlide : 3.4.1(Included in Windows build 20221217:https://github.com/openslide/openslide-bin/releases/tag/v20221217)
TestData: https://zenodo.org/records/4711906/files/Sakuma_year5_VEXAS_bone_marrow_smear.ndpi?download=1(Downloadable from https://zenodo.org/records/4711906)

Looking to the releaase note of OpenSlide 3.4.1, more than 4GB ndpi is supported.
Is this issue still remaining, or Windows build20221217 does not include OpenSlide 3.4.1?

**Comment by taku-i** [comment] 2024-04-16 05:15
Sorry, that might be duplicacte here.(https://github.com/openslide/openslide/issues/174)

**Comment by bgilbert** [comment] 2024-04-17 03:48
Thanks for providing a sample file! Yes, this is a duplicate of #174.  Support for large NDPI files in OpenSlide 3.4.1 and 4.0.0 is based on heuristics that may not work for very large, or newer, slides.  However, reportedly there's a better way to parse these files (https://github.com/openslide/openslide/issues/174#issuecomment-516015219) which will hopefully be implemented in an upcoming release.  I'll close this as a duplicate; thanks for the report.

**Closed by bgilbert** 2024-04-17 03:48 UTC
Labels: defect
