### ISSUE TITLE
Version number is still 3.4.1

### ISSUE THREAD

**Issue by 464hee** [openslide/openslide#452] opened 2023-05-30 01:32 UTC
### Slide format

SVS

### Issue details

From the status of updates in the past few years, openslide still seems to be in a state of update, can you tell me why the version number is still stuck at v3.4.1 in 2015?
When will the next stable version be released, look forward to v3.4.2

**Comment by 464hee** [comment] 2023-05-30 01:32
@bgilbert

**Comment by bgilbert** [comment] 2023-05-30 01:36
Duplicate of #351.

**Closed by bgilbert** 2023-05-30 01:36 UTC
Labels: enhancement
