### ISSUE TITLE
Select areas on an image with openslide

### ISSUE THREAD

**Issue by joelvis-maker** [openslide/openslide#317] opened 2020-11-24 17:13 UTC
## Context

Issue type: Feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): Python version: 1.1.1
**OpenSlide version** (`openslide.__library_version__`): Python version: 1.1.1
**Slide format** (e.g. SVS, NDPI, MRXS): bif

## Details

I'm importing an image with openslide, and there are three images. I'm trying to select some areas with read_region, but it doesn't work. I've tried doing it manually, but it doesn't work either. How can I zoom in on the image to select certain areas? And how can we divide the image into three?

Here is the image I am using:

https://drive.google.com/file/d/1IBpJ9ps_C6i2r9hzwJrktlBFmQOKJgo8/view?usp=sharing

When I use read_region I am unable to select regions. How do you determine a particular region to select?

    slide = ops.OpenSlide('img.bif')
    
    level = 6
    slide_high = slide.read_region((1780,1950), level-1, slide.level_dimensions[level])
    
[Output 1][1]

When I try to separate the images manually, I can't really do it. I separate one image from the rest, but two images stay together

    level = 6
    downsample = int(slide.level_downsamples[level])
    width, height = slide.level_dimensions[level]
    read_size = 4096 
    # Calculate number of vertical and horizontal reads we'll need to take
    vertical_reads = ((height - 1) // read_size) + 1
    horizontal_reads = ((width - 1) // read_size) + 1
    
    # Storage for all of our reads
    all_imgs = []
    
    for v_read in range(vertical_reads):
        for h_read in range(horizontal_reads):
            img = slide.read_region(((h_read * read_size)*downsample, (v_read * read_size)*downsample), level, (read_size, read_size))
            
            img_array = np.asarray(img)
            all_imgs.append(img_array)       
        
    composite_image = np.zeros((vertical_reads * read_size, horizontal_reads * read_size, 4), dtype=np.uint8)
    
    for i in range(vertical_reads):
        for j in range(horizontal_reads):
            
            start_i = i * read_size
            end_i = start_i + read_size
            
            start_j = j * read_size
            end_j = start_j + read_size
            
            composite_image[start_i:end_i, start_j:end_j,:] = all_imgs[(i * horizontal_reads) + j]
    
    
    PIL.Image.fromarray(all_imgs[0])

[Output 2][2]

  [1]: https://i.stack.imgur.com/RXeae.jpg
  [2]: https://i.stack.imgur.com/ix9ws.jpg

**Comment by bgilbert** [comment] 2020-11-27 20:05
Closing as duplicate of https://github.com/openslide/openslide-python/issues/106.

**Closed by bgilbert** 2020-11-27 20:05 UTC
