### ISSUE TITLE
empty tiles on macOS

### ISSUE THREAD

**Issue by pavertomato** [openslide/openslide#268] opened 2019-04-02 13:30 UTC
## Context

**Issue type** (bug report or feature request): 
bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
Mac OS 10.14.3; 10.10.5
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
64-bit x86
**OpenSlide version**: 
3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 
SVS

## Details
OpenSlide returns empty region for first row and first column of image on last level, except location (0,0)

locations (0,Y) and (X,0) empty, but (1,Y) (X,1) returns correct image, this may be reproduced in C library and in python API as well, please find python script in attachment, on linux and windows this script generate correct tiles for first two rows of last level, but on MacOS tiles damaged as described (reproducible  on http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1.svs)
**CMU-1svs0_0(macos)**
![CMU-1 svs0_0(macos)](https://user-images.githubusercontent.com/878990/55406097-a6440e00-5585-11e9-973d-904e35a2acf9.jpeg)
**CMU-1svs0_500(macos)**
![CMU-1 svs0_500(macos)](https://user-images.githubusercontent.com/878990/55406131-b5c35700-5585-11e9-8e40-b51146072e92.jpeg)
**CMU-1svs0_500(linux)**
![CMU-1 svs0_500(linux)](https://user-images.githubusercontent.com/878990/55406173-c542a000-5585-11e9-872a-1b4234a95be4.jpeg)

[firstRowBug.py.txt](https://github.com/openslide/openslide/files/3034116/firstRowBug.py.txt)

**Comment by jxu** [comment] 2019-07-05 04:18
Maybe issue with RGB conversion. Have you tried just `tile.convert("RGB")`

**Comment by pavertomato** [comment] 2019-07-08 13:29
> tile.convert("RGB")

result exactly the same, seems like blank pixels returned by osr.read_region

**Comment by fireofearth** [comment] 2019-09-25 19:30
I'm experiencing this too. I made an issue for `openslide-python` here:
<https://github.com/openslide/openslide-python/issues/58>

**Comment by pavertomato** [comment] 2019-09-25 19:47
> I'm experiencing this too. I made an issue for `openslide-python` here:
> [openslide/openslide-python#58](https://github.com/openslide/openslide-python/issues/58)

i'm sure what this issue not related with python wrapper, because i get same error by calling openslide lib from c++ code, but may be this may help to fix it
unfortunately i didn't had enough free time to find root cause by myself

**Comment by infinet** [comment] 2019-12-08 23:26
I have similar problem on Linux. When start locations is (X,0) or (0, Y), where X, Y > 96, the tile from level 2 is empty. It may caused by cairo. Cairo version 1.14.8 and 1.14.6 works, but 1.14.10 / 1.14.12 / 1.16.0 all return empty tile.

**Comment by bgilbert** [comment] 2022-09-06 07:33
Closing as duplicate of #278.  See https://github.com/openslide/openslide/issues/278#issuecomment-1237765515 for the current status.

**Closed by bgilbert** 2022-09-06 07:33 UTC
